projeto/estoque/conf/urls.py
from django.contrib import admin 
from django.urls import path, include 
from core.views import index 
urlpatterns = [ 
path('', index, name='index'), 
#path('produto/', include('produto.urls', namespace='produto')), 
path('admin/', admin.site.urls), 
]

projeto/estoque/entrada/urls.py
from django.urls import path 
from .views import list_entrada, new_entrada, update_entrada, delete_entrada 
 
app_name = 'entrada' 
 
urlpatterns = [ 
 path('list_entrada/', list_entrada, name='list_entrada'), 
 path('new_entrada/', new_entrada, name='new_entrada'), 
 path('update_entrada/<int:pk>/', update_entrada, name='update_entrada'), 
 path('delete_entrada/<int:pk>/', delete_entrada, name='delete_entrada'), 
] 

projeto/estoque/produto/urls.py
from django.urls import path 
from .views import list_produto, new_produto, update_produto, delete_produto 
app_name = 'produto' 
urlpatterns = [ 
    path('list_produto/', list_produto, name='list_produto'), 
    path('new_produto/', new_produto, name='new_produto'), 
    path('update_produto/<int:pk>/', update_produto, 
name='update_produto'), 
    path('delete_produto/<int:pk>/', delete_produto, 
name='delete_produto'), 
] 

projeto/estoque/core/models.py
from django.db import models

# Create your models here.
from django.db import models 
class Cores(models.Model): 
    cor = models.CharField('Cor', max_length=200) 
    def __str__(self): 
        return self.cor 
class Produtos(models.Model): 
    produto = models.CharField('Produto', max_length=200) 
    cor = models.ForeignKey(Cores, on_delete=models.PROTECT, 
verbose_name='Cor') 
    descricao = models.TextField('Descrição', blank=True) 
    preco = models.DecimalField('Preço', decimal_places=2, 
max_digits=8, default=0) 
    quantidade = models.IntegerField('Quantidade', default=0) 
    criado = models.DateTimeField('Criado em', auto_now_add=True) 
    modificado = models.DateTimeField('Modificado em', auto_now=True) 
def __str__(self): 
    return self.produto 
def precoQuantidade(self): 
    return self.preco * self.quantidade 
class Meta: 
    verbose_name = 'Produto' 
    verbose_name_plural = 'Produtos' 
    ordering = ['-produto']

projeto/estoque/entrada/models.py
from django.db import models 
from produto.models import Produtos 
class Entradas(models.Model): 
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE, verbose_name='Produto') 
    preco = models.FloatField('Preço', default=0) 
    quantidade = models.IntegerField('Quantidade', default=0) 
    criado = models.DateTimeField('Criado em', auto_now_add=True) 
    modificado = models.DateTimeField ('Modificado em', auto_now=True)

projeto/estoque/produto/models.py
from django.db import models 
class Cores(models.Model): 
    cor = models.CharField('Cor', max_length=200) 
    def __str__(self): 
        return self.cor 
class Produtos(models.Model): 
    produto = models.CharField('Produto', max_length=200) 
    cor = models.ForeignKey(Cores, on_delete=models.PROTECT, 
verbose_name='Cor') 
    descricao = models.TextField('Descrição', blank=True) 
    preco = models.DecimalField('Preço', decimal_places=2, 
max_digits=8, default=0) 
    quantidade = models.IntegerField('Quantidade', default=0) 
    criado = models.DateTimeField('Criado em', auto_now_add=True) 
    modificado = models.DateTimeField('Modificado em', auto_now=True) 
    def __str__(self): 
        return self.produto 
    def precoQuantidade(self): 
        return self.preco * self.quantidade 
    class Meta: 
        verbose_name = 'Produto' 
        verbose_name_plural = 'Produtos' 
        ordering = ['-produto']

projeto/estoque/entrada/forms.py
from django.forms import ModelForm 
from .models import Entradas 
class EntradaForm(ModelForm): 
    class Meta: 
        model = Entradas 
        fields = ['produto', 'quantidade', 'preco']

projeto/estoque/produto/forms.py
from django.forms import ModelForm 
from .models import Produtos 
class ProdutoForm(ModelForm): 
    class Meta: 
        model = Produtos 
        fields = ['produto', 'cor', 'descricao']

projeto/estoque/core/views.py
from django.shortcuts import render

# Create your views here.

def index(request): 
    template_name = 'index.html' 
    context = { 
        'mensagem': 'Bem vindo à aplicação estoqueWeb' 
} 
    return render(request, template_name, context)

projeto/estoque/entrada/views.py
from django.shortcuts import render, redirect 
from .models import Entradas 
from .forms import EntradaForm 
 
def list_entrada(request): 
    entradas = Entradas.objects.all() 
    template_name = 'list_entrada.html' 
    context = { 
        'entradas': entradas, 
    } 
    return render(request, template_name, context)
def new_entrada(request): 
    if request.method == 'POST': 
        form = EntradaForm(request.POST) 
    if form.is_valid(): 
        form.save(commit=False) 
        form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + form.cleaned_data['quantidade'] 
        form.cleaned_data['produto'].preco = form.cleaned_data['preco'] 
        form.cleaned_data['produto'].save_base() 
        form.save() 
        return redirect('entrada:list_entrada') 
    else: 
        template_name = 'new_entrada.html' 
        context = { 
            'form': EntradaForm(), 
} 
        return render(request, template_name, context) 

def update_entrada(request, pk): 
    entrada = Entradas.objects.get(pk=pk) 
    quantidade = entrada.quantidade 
    print('==> ', quantidade) 
    if request.method == 'POST': 
        form = EntradaForm(request.POST, instance=entrada) 
        if form.is_valid(): 
            print('===> ', quantidade,form.cleaned_data['quantidade']) 
            form.save(commit=False) 
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - quantidade + form.cleaned_data['quantidade'] 
            form.cleaned_data['produto'].save_base() 
            form.save() 
            return redirect('entrada:list_entrada') 
        else: 
            template_name = 'update_entrada.html' 
            context = { 
        'form': EntradaForm(instance=entrada), 
        'pk': pk, 
} 
        return render(request, template_name, context) 
def delete_entrada(request, pk): 
    entrada = Entradas.objects.get(pk=pk) 
    entrada.produto.quantidade = entrada.produto.quantidade - entrada.quantidade 
    entrada.produto.save() 
    entrada.delete() 
    return redirect('entrada:list_entrada')

projeto/estoque/produto/views.py
from django.shortcuts import render, redirect 
from .models import Produtos 
from .forms import ProdutoForm 
 
def list_produto(request): 
  produtos = Produtos.objects.all() 
  template_name = 'list_produto.html' 
  context = { 
    'produtos': produtos, 
  } 
  return render(request, template_name, context) 
 
def new_produto(request): 
  if request.method == 'POST': 
    form = ProdutoForm(request.POST) 
    if form.is_valid(): 
      form.save() 
      return redirect('index') 
  else: 
    template_name = 'new_produto.html' 
    context = { 
      'form': ProdutoForm(), 
    } 
    return render(request, template_name, context) 
def update_produto(request, pk): 
  produto = Produtos.objects.get(pk=pk) 
  if request.method == 'POST': 
    form = ProdutoForm(request.POST, instance=produto) 
    if form.is_valid(): 
      form.save() 
      return redirect('index') 
  else: 
    template_name = 'update_produto.html' 
    context = { 
      'form': ProdutoForm(instance=produto), 
      'pk': pk, 
    } 
    return render(request, template_name, context) 
 
def delete_produto(request, pk): 
  produto = Produtos.objects.get(pk=pk) 
  produto.delete() 
  return redirect('index')

projeto/estoque/core/templates/base.html
<!DOCTYPE html> 
{% load static %} 
<html lang="pt-br"> 
<head> 
<meta charset="UTF-8"> 
<meta name="viewport" content="width=device-width, 
initial-scale=1.0"> 
<title>Django</title> 
</head> 
<body> 
<h1>Responsive Horizontal-to-Scrollable Menu</h1> 
{% block product %}{% endblock %} 
</body> 
</html>

projeto/estoque/core/templates/index.html
{% extends 'base.html' %} 
{% block product %} 
<h1>Aplicação estoqueWeb</h1> 
<p>Praesent sapien massa, convallis a pellentesque nec, 
egestas non nisi. Praesent sapien massa, convallis a 
pellentesque nec, egestas non nisi. Sed porttitor lectus nibh. 
Vivamus magna justo, lacinia eget consectetur sed, convallis 
at tellus. Proin eget to rtor risus. Vivamus suscipit tortor 
eget felis porttitor volutpat. Nulla porttitor accumsan 
tincidunt. Nulla porttitor accumsan tincidunt. Vestibulum ante 
ipsum primis in faucibus orci luctus et ultrices posuere 
cubilia Curae; Donec velit neque, auctor sit ametaliquam vel, 
ullamcorper sit amet ligula. Praesent sapien massa, convallis 
a pellentesque nec, egestas non nisi.</p> 
{% endblock %}

projeto/estoque/core/templates/list_produto.html
{% extends 'base.html' %} 
{% block product %} 
  <p>Produto</p> 
  <a href="{% url 'produto:new_produto' %}">Novo</a> 
  <table> 
    <thead> 
      <tr> 
        <th>Id</th> 
        <th>Produto</th> 
        <th>Cor</th> 
        <th>Preço</th> 
        <th>Quantidade</th> 
        <th></th> 
      </tr> 
    </thead>
    <tbody> 
        {% for produto in produtos %} 
          <tr> 
            <th>{{ produto.id }}</th> 
            <td>{{ produto.produto }}</td> 
            <td>{{ produto.cor }}</td> 
            <td>{{ produto.preco }}</td> 
            <td>{{ produto.quantidade }}</td> 
            <td><a href="{% url 'produto:update_produto' produto.id 
    %}">alterar</a></td> 
            <td><a href="{% url 'produto:delete_produto' produto.id 
    %}">deletar</a></td> 
          </tr> 
        {% endfor %} 
        </tbody> 
      </table> 
    {% endblock %} 

projeto/estoque/core/templates/new_protuto.html
{% extends 'base.html' %} 
{% block product %} 
  <p>Novo produto</p> 
  <form action="{% url 'produto:new_produto' %}" method="POST"> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <button type="submit">salvar</button> 
  </form> 
{% endblock %}

projeto/estoque/core/templates/update_protudo.html
{% extends 'base.html' %} 
{% block product %} 
<p>Alterar produto</p> 
<form action="{% url 'produto:update_produto' pk %}" method="post"> 
{% csrf_token %} 
{{ form.as_p }} 
<button type="submit">Salvar</button> 
</form> 
{% endblock %}

projeto/estoque/entrada/templates/list_entrada.html
{% extends 'base.html' %} 
{% block product %} 
<p>Entrada</p> 
<a class="button is-primary" href="{% url 'entrada:new_entrada' 
%}">Novo</a> 
<table class="table"> 
    <thead> 
        <tr> 
            <th>Id</th> 
            <th>Produto</th> 
            <th>Preço</th> 
            <th>Quantidade</th> 
            <th></th> 
        </tr> 
    </thead> 
    <tbody> 
        {% for entrada in entradas %} 
        <tr> 
            <th>{{ entrada.id }}</th> 
            <td>{{ entrada.produto }}</td> 
            <td>{{ entrada.preco }}</td> 
            <td>{{ entrada.quantidade }}</td> 
            <td><a class="button is-primary" href="{% url 
'entrada:update_entrada' entrada.id %}">alterar</a></td> 
            <td><a class="button is-primary" href="{% url 
'entrada:delete_entrada' entrada.id %}">deletar</a></td> 
        </tr> 
        {% endfor %} 
    </tbody> 
</table> 
{% endblock %}

projeto/estoque/entrada/templates/new_entrada.html
{% extends 'base.html' %} 
{% block product %} 
<p>Nova Entrada</p> 
<form action="{% url 'entrada:new_entrada' %}" method="POST"> 
{% csrf_token %} 
{{ form.as_p }} 
<button class="button is-primary" type="submit">salvar</button> 
</form> 
{% endblock %}

projeto/estoque/entrada/templates/update_entrada.html
{% extends 'base.html' %} 
{% block product %} 
<p>Alterar entrada</p> 
<form action="{% url 'entrada:update_entrada' pk %}" method="post"> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <button class="button is-primary" type="submit">Salvar</button> </form> 
{% endblock %}